### ISSUE TITLE
PWA icon settings inside manfest.json doesn't work

### ISSUE THREAD

**Issue by amirihusayn** [codegeeks-ir/codegeeks-ir#53]

**Comment by amirihusayn** [comment]
Thanks in advance for your help.

**Comment by akansjain** [comment]
@amirihusayn can you please explain the issue with a screenshot?

**Comment by amirihusayn** [comment]
PWA install popup is not showing. Also browser says 404 manifest.json not found.

**Comment by akansjain** [comment]
@amirihusayn , I am looking into the issue give me couple of days.

**Comment by amirihusayn** [comment]
> @amirihusayn , I am looking into the issue give me couple of days.

I have to inform that We are using `next-pwa` package.

**Comment by mohsenfaraj** [comment]
Issue is fixed in #8daeb58

**Comment by mohsenfaraj** [comment]
Issue is resolved in commit `8daeb58`. Moving manifest to the proper location fixed it.
